version: '3.8'
services:
  db:
    image: bitnami/postgresql:16.2.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cafeteriav4
    volumes:
      - db-dat:/db-dat
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:8.4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  db-dat: